"""empty message

Revision ID: 0b10d67750be
Revises: bd383e73ef4d
Create Date: 2026-06-04 20:43:11.273119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b10d67750be'
down_revision = 'bd383e73ef4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_refresh_token_id'), ['refresh_token_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_refresh_token_id'))
    # ### end Alembic commands ###
