"""empty message

Revision ID: 144524c5cf79
Revises: ae608469ef8b
Create Date: 2022-09-13 13:41:30.316063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144524c5cf79'
down_revision = 'ae608469ef8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
