"""datetime in planner

Revision ID: 1d3c1e2061f6
Revises: 22dbfbf4cc33
Create Date: 2025-02-23 21:11:07.978331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3c1e2061f6'
down_revision = '22dbfbf4cc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('day')
        batch_op.drop_constraint('pk_planner') # manually added
        batch_op.create_primary_key('pk_planner', ['recipe_id', 'cooking_date'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.INTEGER(), nullable=False))
        batch_op.drop_column('cooking_date')
        batch_op.drop_constraint('pk_planner') # manually added
        batch_op.create_primary_key('pk_planner', ['recipe_id', 'day'])

    # ### end Alembic commands ###
