"""empty message

Revision ID: 22dbfbf4cc33
Revises: fcd7cff0aea2
Create Date: 2024-11-20 11:46:59.071313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dbfbf4cc33'
down_revision = 'fcd7cff0aea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_column('budget')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
