"""empty message

Revision ID: 23445ea65b2b
Revises: 6d6984e216ff
Create Date: 2021-04-09 16:40:19.462601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23445ea65b2b'
down_revision = '6d6984e216ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('planned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'planned')
    # ### end Alembic commands ###
