"""empty message

Revision ID: 3d3333ffb91e
Revises: 6c1be50bb858
Create Date: 2021-08-18 10:13:11.745182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3333ffb91e'
down_revision = '6c1be50bb858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('suggestion_rank', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'suggestion_rank')
    # ### end Alembic commands ###
