"""datetime in planner

Revision ID: 4f7507bf20d4
Revises: 22dbfbf4cc33
Create Date: 2025-02-16 17:28:17.501371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7507bf20d4'
down_revision = '22dbfbf4cc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when', sa.DateTime(), nullable=False))
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.INTEGER(), nullable=False))
        batch_op.drop_column('when')

    # ### end Alembic commands ###
