"""empty message

Revision ID: 7464b5211b10
Revises: 0b10d67750be
Create Date: 2026-07-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7464b5211b10'
down_revision = '0b10d67750be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_store_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store'))
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_household_id'), ['household_id'], unique=False)

    op.create_table('item_stores',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_stores_item_id_item')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_item_stores_store_id_store')),
    sa.PrimaryKeyConstraint('item_id', 'store_id', name=op.f('pk_item_stores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_stores')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_household_id'))

    op.drop_table('store')
    # ### end Alembic commands ###
