"""empty message

Revision ID: 8f12363abaaf
Revises: c63508852dd1
Create Date: 2023-11-06 14:46:20.697901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f12363abaaf'
down_revision = 'c63508852dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_mail_verify',
    sa.Column('challenge_hash', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_challenge_mail_verify_user_id_user')),
    sa.PrimaryKeyConstraint('challenge_hash', name=op.f('pk_challenge_mail_verify'))
    )
    op.create_table('challenge_password_reset',
    sa.Column('challenge_hash', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_challenge_password_reset_user_id_user')),
    sa.PrimaryKeyConstraint('challenge_hash', name=op.f('pk_challenge_password_reset'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    op.drop_table('challenge_password_reset')
    op.drop_table('challenge_mail_verify')
    # ### end Alembic commands ###
