"""datetime in planner 2

Revision ID: 8fd76e826ca2
Revises: 4f7507bf20d4
Create Date: 2025-02-23 16:41:32.085715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd76e826ca2'
down_revision = '4f7507bf20d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('when')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when', sa.DATETIME(), nullable=False))
        batch_op.drop_column('cooking_date')

    # ### end Alembic commands ###
