"""datetime in planner

Revision ID: c505a2ba7105
Revises: 22dbfbf4cc33
Create Date: 2025-02-15 16:09:27.535743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c505a2ba7105'
down_revision = '22dbfbf4cc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_column('when')

    # ### end Alembic commands ###
