"""empty message

Revision ID: c63508852dd1
Revises: dedd014b6a59
Create Date: 2023-10-04 12:36:55.881848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63508852dd1'
down_revision = 'dedd014b6a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_household_id'), ['household_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_household_id'), ['household_id'], unique=False)

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planner_household_id'), ['household_id'], unique=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_household_id'), ['household_id'], unique=False)

    with op.batch_alter_table('shoppinglist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shoppinglist_household_id'), ['household_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoppinglist_household_id'))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_household_id'))

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planner_household_id'))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_household_id'))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_household_id'))

    # ### end Alembic commands ###
