"""empty message

Revision ID: dedd014b6a59
Revises: ade9ad0be1a5
Create Date: 2023-10-03 17:33:03.605572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedd014b6a59'
down_revision = 'ade9ad0be1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_household_id'), ['household_id'], unique=False)
    if "postgresql" in bind.engine.name:
        op.execute("CREATE EXTENSION fuzzystrmatch")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_household_id'))
    if "postgresql" in bind.engine.name:
        op.execute("DROP EXTENSION fuzzystrmatch")

    # ### end Alembic commands ###
