"""empty message

Revision ID: e209fcb83993
Revises: 29381d24ec31
Create Date: 2022-03-19 13:39:54.518323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e209fcb83993'
down_revision = '29381d24ec31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'source')
    # ### end Alembic commands ###
