"""Add Inventory

Revision ID: f5a5571d9a06
Revises: bd383e73ef4d
Create Date: 2026-04-06 14:15:27.103655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
DeclarativeBase = orm.declarative_base()


# revision identifiers, used by Alembic.
revision = 'f5a5571d9a06'
down_revision = 'bd383e73ef4d'
branch_labels = None
depends_on = None



class Household(DeclarativeBase):
    __tablename__ = "household"

    id = sa.Column(sa.Integer, primary_key=True)
    inventory_feature = sa.Column(sa.Boolean)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_inventory_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_household_id'), ['household_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_inventory_items_created_by_user')),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_inventory_items_inventory_id_inventory')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_inventory_items_item_id_item')),
    sa.PrimaryKeyConstraint('inventory_id', 'item_id', name=op.f('pk_inventory_items'))
    )

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_feature', sa.Boolean(), nullable=True))

    # Data migration
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    households = session.query(Household).all()
    for household in households:
        household.inventory_feature = False

    try:
        session.bulk_save_objects(households)
        session.commit()
    except Exception as e:
        session.rollback()
        raise e
    # Data migration end

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.alter_column('inventory_feature', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_column('inventory_feature')

    op.drop_table('inventory_items')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_household_id'))

    op.drop_table('inventory')
    # ### end Alembic commands ###
