"""empty message

Revision ID: fe3a5c9ac84c
Revises: ade6487fe28a
Create Date: 2022-10-18 17:26:44.087997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3a5c9ac84c'
down_revision = 'ade6487fe28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('yields', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('yields')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('cook_time')

    # ### end Alembic commands ###
