"""empty message

Revision ID: 5140d8f9339b
Revises: 3d667fcc5581
Create Date: 2023-07-02 12:19:57.117736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5140d8f9339b'
down_revision = '3d667fcc5581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shoppinglist_items_created_by_user'), 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglist_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shoppinglist_items_created_by_user'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
