"""empty message

Revision ID: 55fe25bdf42b
Revises: a9824159e4e5
Create Date: 2022-12-08 17:41:24.521923

"""
from alembic import op
import sqlalchemy as sa

import app.helpers.db_set_type

# revision identifiers, used by Alembic.
revision = '55fe25bdf42b'
down_revision = 'a9824159e4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_ordering', app.helpers.db_list_type.DbListType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('view_ordering')

    # ### end Alembic commands ###
