"""empty message

Revision ID: fffa4ab33d2a
Revises: 22d528c529ca
Create Date: 2021-03-04 17:42:36.395179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffa4ab33d2a'
down_revision = '22d528c529ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_items', sa.Column('optional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_items', 'optional')
    # ### end Alembic commands ###
