name:  Quality

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter packages get

      # Run analyze
      - run: flutter analyze
      - uses: leancodepl/dart-problem-matcher@main
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter packages get

      # Run tests
      - run: flutter test --machine > test-results.json

      # upload test results
      - uses: actions/upload-artifact@v3
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: test-results.json
